### ISSUE TITLE
plugin eofnewline

### ISSUE THREAD

**Issue by SwissalpS** [bokunodev/lite_modules#1]
press ctrl+s multiple times after each other and watch the last line. Every second time there are two newlines at end of file.

**Comment by bokunodev** [comment]
yeah, inoticed it.
fixed in this commit https://github.com/bokunodev/lite_modules/commit/a4d0b6697479b0cd5313ba9f2d1e27041331cd8a

**Comment by SwissalpS** [comment]
[In line 13](https://github.com/bokunodev/lite_modules/blob/db3ba73dc7e0dfd52a8f74d1d0adb50b926c4cf0/plugins/eofnewline.lua#L13) ([line 12 in my version](https://github.com/SwissalpS/lite/blob/8a1f0465f5003729a36f4bafbd44f5941ddbd0b0/data/plugins/eofnewline.lua#L12) I have doc:remove(neof, 1, leof, math.huge)
Start remove at char 1 not eol (math.huge)
If it works for you, then fine :D
